### ISSUE TITLE
Curved text along a path

### ISSUE THREAD

**Issue by sepultanic** [yWorks/svg2pdf.js#33] opened 2017-10-11 22:50 UTC
I encounter problems when I try to convert svg containing circular texts along a path. I uploaded a file that shows this problem. Are the textPath supported or will it be in the future?

![svg2pdf](https://user-images.githubusercontent.com/32720864/31471205-e9860286-aee7-11e7-9edb-f33351623c8e.jpg)

**Comment by yGuy** [comment] 2017-10-12 06:20
It's not implemented and not planned, but we are open to pull requests.

**Comment by HackbrettXXX** [comment] 2020-09-23 14:27
Duplicate of #152.

**Closed** 2020-09-23 14:27 UTC
Labels: enhancement, help wanted
