### ISSUE TITLE
Svg-text with custom font is not exported to pdf

### ISSUE THREAD

**Issue by anneeberle** [yWorks/svg2pdf.js#64] opened 2018-11-09 15:22 UTC
When i try to convert a text with font "Prada Regular", the text does not appear in the PDF

To reproduce use attached sample with jsPDF (commit 2f18d0f) and svg2pdf (commit  1dcf2e4).
[missing-label_html.txt](https://github.com/yWorks/svg2pdf.js/files/2566371/missing-label_html.txt)

At the top the SVG-input is displayed and a PDF preview is shown below.
While the rectangle is exported correctly, the text is missing.

I worked with Chrome Version 70.0.3538.77 on Windows 10.

**Comment by fskpf** [comment] 2018-11-21 16:55
This seems to be related to the utilized font. The test case, i.e. /tests/custom-fonts.html in this repo still works (Batang.ttf), as well as the other embedded font in the attached test case of @anneeberle (mplus-1c-regular.ttf). However, the Prata-Regular.ttf is not working at all.

I've also tried it with another font in another project (Roboto.ttf) which does not work either, though there are some gibberish characters printed when used with greek or cyrillic chars. 
(Tested with the 'master' of svg2pdf and jspdf).

Note that all of the above worked with previous versions of svg2pdf (/dist/ changeset a955ee8) and jsPDF (/dist/ changeset dfa618c). So this looks like a regression to me.

**Comment by HackbrettXXX** [comment] 2019-01-16 15:49
Was an issue of jsPDF (see https://github.com/yWorks/jsPDF/issues/18), which is now fixed

**Closed by HackbrettXXX** 2019-01-16 15:49 UTC
