### ISSUE TITLE
Not rendering and broken pdf with `font-size="smaller"`

### ISSUE THREAD

**Issue by bernhardreiter** [yWorks/svg2pdf.js#103] opened 2019-07-04 15:38 UTC
Trying to render an svg, some elements are not rendered correctly.
Ideas is the rotate of the "Sum of days"
Using 100f3c6f83980811f9ae4dc32e8830983ab03b64 (HEAD -> master)

**Comment by bernhardreiter** [comment] 2019-07-04 15:39
[test103-bad.pdf](https://github.com/yWorks/svg2pdf.js/files/3359907/test103-bad.pdf)
[test103.html.txt](https://github.com/yWorks/svg2pdf.js/files/3359908/test103.html.txt)

**Comment by HackbrettXXX** [comment] 2019-07-04 15:56
The issue is `font-size="smaller"`. We only support pixel values here. So this is kind of a duplicate of #101.

**Comment by bernhardreiter** [comment] 2019-07-05 07:14
When used in our vuejs application with this SVG the application is send in an endless loop. This should not happen, even if some feature is not supported. (#95 which is closed by #101 is about different measurement units in the jsPDF object, if `font-size="smaller"` is the problem, it would be about unsupported relative units.)

**Comment by bernhardreiter** [comment] 2019-07-05 07:21
Confirmation from my side that replacing `"smaller"` with `"9"` will lead to the full SVG rendered in chromium and rendered at all in a libpoppler based viewer!

So this is a known issue of "not supporting most other units than `px` (or `pt` for that matter)" mentioned in #82.

@HackbrettXXX thanks for your hint!

**Comment by HackbrettXXX** [comment] 2019-07-05 08:03
> (#95 which is closed by #101 is about different measurement units in the jsPDF object, if font-size="smaller" is the problem, it would be about unsupported relative units.)

Sorry I meant #100 

I'm closing this as a duplicate of #100.

**Closed by HackbrettXXX** 2019-07-05 08:03 UTC

**Comment by bernhardreiter** [comment] 2019-07-05 08:26
The difference between #100 and this one is that in case of `"1em"` there is still a text seen and a valid pdf. But I guess that `"em"` will have the same problem, so it is close enough.
