### ISSUE TITLE
Uncaught TypeError: pt.saveGraphicsState is not a function

### ISSUE THREAD

**Issue by guidev224** [yWorks/svg2pdf.js#53] opened 2018-07-07 10:31 UTC
Hi,
I am trying to use this library to export an svg element content  as pdf but I am getting this error
**Uncaught TypeError: pt.saveGraphicsState is not a function** even though I have added the jsPDF library

Any help??
Thanks in advance

**Comment by yGuy** [comment] 2018-07-07 10:33
Duplicate of #50

**Closed by yGuy** 2018-07-07 10:33 UTC

**Comment by guidev224** [comment] 2018-07-07 11:00
@yGuy thanks for your quick answer,
Even though I have added your jsPDF version I am still getting the same error.
I have replaced the content of my local file by the your file content, but same error

**Comment by yGuy** [comment] 2018-07-09 07:06
If you use the jsPDF file from the "dist" folder (which is the one that contains all of the code) your sample works for me: https://github.com/yWorks/jsPDF/blob/master/dist/jspdf.min.js

And rep*r*o means "reproduction case": instructions that let others reproduce your findings.

**Comment by guidev224** [comment] 2018-07-09 08:05
Hi @yGuy ,
After adding the https://github.com/yWorks/jsPDF/blob/master/dist/jspdf.min.js file the issue is resolved, but another one prompted : **Uncaught TypeError: Cannot read property 'cloneNode' of null**.
You can check the repository I am working on [here](https://github.com/guidev224/svg2pdf)
