### ISSUE TITLE
Building the the library fails

### ISSUE THREAD

**Issue by Fadiabb** [yWorks/svg2pdf.js#91] opened 2019-06-11 11:56 UTC
After check out the repository, i used the instructions to build the minified files with yarn and npm:
`npm run build`  / `yarn build` throws the following Error:
Error: Cannot find module 'SvgPath' from '/home/fabbud/svg2pdf.js/src' at /home/fabbud/svg2pdf.js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17

execute `yarn browserify:svgpath` / ` npm run browserify:svgpath` initialize the SvgPath 
$ browserify node_modules/svgpath/index.js -s SvgPath -o src/SvgPath.js
Done in 1.20s.
then 
`yarn run browserify`  or `yarn build` will give the same above error.

yarn version v1.16.0

**Comment by HackbrettXXX** [comment] 2019-06-12 08:14
I cannot reproduce this. I created a fresh clone, ran `npm/yarn run build` and everything works fine. Did you maybe forget to run `npm install`/`yarn` after cloning?

**Comment by bernhardreiter** [comment] 2019-06-12 09:15
@HackbrettXXX thanks for checking.

We did an `npm install` or `yarn` before running the build. I'm also investigating. 

This failed on an Ubuntu 18.04.2 LTS system with node.js coming from the original packages.
My next idey is looking into browserify and an elder nodejs version problems. Otherwise we just put in the patches into the current build version for testing #87.

**Comment by HackbrettXXX** [comment] 2019-06-12 11:48
I tested on a Windows 10 machine. Maybe the npm scripts don't run properly in Ubuntu? Could you check if the individual scripts work or if manually entering the commands makes a difference?

**Comment by bernhardreiter** [comment] 2019-06-12 12:45
```sh
node node_modules/browserify/bin/cmd.js node_modules/svgpath/index.js -s SvgPath -o src/SvgPath.js
```
works, but the next one fails

```sh
node node_modules/browserify/bin/cmd.js src/svg2pdf.js --debug -p licensify -s svg2pdf -o dist/svg2pdf.js

Error: Cannot find module 'SvgPath' from '/home/ber/svg2pdf.js/src'
    at /home/ber/svg2pdf.js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/ber/svg2pdf.js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/ber/svg2pdf.js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/ber/svg2pdf.js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ber/svg2pdf.js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ber/svg2pdf.js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:154:21)
```

**Comment by HackbrettXXX** [comment] 2019-06-12 13:53
Is `SvgPath` in `node_modules`? If yes, this seems to be an issue of Browserify or Node. I'm closing this issue, if you still think it's an issue with this repo, we can reopen the issue.

**Comment by bernhardreiter** [comment] 2019-06-12 14:12
Found a solution to the problem:

```diff
diff --git a/src/svg2pdf.js b/src/svg2pdf.js
index 56e1276..f792422 100644
--- a/src/svg2pdf.js
+++ b/src/svg2pdf.js
@@ -2325,7 +2325,7 @@ SOFTWARE.
     });
   } else if (typeof module !== "undefined" && module.exports) {
     RGBColor = require("./rgbcolor.js");
-    SvgPath = require("SvgPath");
+    SvgPath = require("svgpath");
     FontFamily = require("font-family-papandreou");
     cssEsc = require("cssesc");
     module.exports = svg2pdf;
```

It is likely that the file system @HackbrettXXX uses is **case-insensitive**, but if you are using a case-sensitive file system `SvgPath` does not match. The instructions at https://github.com/fontello/svgpath/blob/master/README.md were `svgpath` is lower-case.

**Comment by yGuy** [comment] 2019-06-12 14:46
A @bernhardreiter  - you beat me! Thanks for your help!

**Comment by HackbrettXXX** [comment] 2019-06-12 14:47
We should probably change the casing in the amd `define` call, as well.

**Comment by bernhardreiter** [comment] 2019-06-12 15:40
@yGuy no problem, thanks for svg2pdf in the first place!

@HackbrettXXX good point, I've updated the pull-request #92 accordingly. (Though not tested, because I haven't checking how to run this code path.)

**Closed** 2019-06-12 16:08 UTC
